### PR TITLE
Add additional artifact path for bugmon hooks

### PR DESCRIPTION
**Pull request by pyoor**
Store entries from `/tmp/grizzly` as artifacts.

### CODE REVIEW

**Review by matt-boris — APPROVED** [review]
LGTM as long as it's fine storing in the `/tmp` directory? I don't see that being used anywhere else in the repo, so for consistency, I think `/grizzly-artifacts` may be better.

**Comment by pyoor** [comment]
@matt-boris, sorry but I'm not sure I follow.  Are you referencing the fact that I'm creating artifacts for files in `/tmp/grizzly` or the location of the indexed artifact?  We're using similar paths in our fuzzing hooks.  See [here](https://community-tc.services.mozilla.com/tasks/d8JjEQo9RAGmabC3fGAIpA/definition).

**Comment by matt-boris** [comment]
@pyoor I was referring to the former. Wasn't sure if it was a standard used or not, which is why I brought it up. Thanks, LGTM 👍🏻

**Comment by matt-boris** [comment]
Applied!

```
Updating Hook=project-fuzzing/bugmon-confirm
Updating Hook=project-fuzzing/bugmon
```

**Pull request merged**
