### PR TITLE
Add CI-Automation project

### PR DESCRIPTION
**Pull request by armenzg**
I still need the ability to create secrets and hooks. So far I'm missing scopes.

### CODE REVIEW

**Comment by tomprince** [comment]
"CI Automation" https://chat.mozilla.org/#/room/#cia:mozilla.org

I believe it is the successor to the a-team, and deals with all the test automation, as well as treeherder.

**Comment by djmitche** [comment]
Thanks!  I have heard of it without the dash, just didn't translate in my head.

**Comment by armenzg** [comment]
/me face-palms

No wonder the commands was not showing any diffs 😄

**Comment by djmitche** [comment]
Looks good, just fix up the yamllint?

**Comment by djmitche** [comment]
Applied!  Please create the secret ASAP, as otherwise tc-admin complains that it isn't there..

**Pull request merged**
