### PR TITLE
Worker pool proj-taskcluster/gw-ci-windows-2022 m5.2xlarge -> c6in.8xlarge

### PR DESCRIPTION
**Pull request by petemoore**
Let's see if this speeds up the Generic Worker builds/tests on Windows 2022!

### CODE REVIEW

**Review by matt-boris — APPROVED** [review]
🤞🏻

**Review by matt-boris — APPROVED** [review]
Thanks Pete!

**Comment by petemoore** [comment]
Applied!
```
Updating WorkerPool=proj-taskcluster/gw-ci-windows-2022
```

**Comment by matt-boris** [comment]
Still sorta long..

https://community-tc.services.mozilla.com/tasks/FoiczGZ_QgS4SfjxWPQcjw/runs/0

**Pull request merged**
