### PR TITLE
Allow bugbug hooks to send emails

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by jwhitlock** [comment]
I am still learning about `tc-admin` and scopes, and I need to do a little more research before approval or solid suggestions.

Looking at the output of the `tc-admin diff` test, it appears that the changes from PR #410 have not yet been applied. I also see no changes related to this PR, such as adding a ``notify:email:*`` scope. Is this because the ancestors don't have that permission? It seems there is a limited set of admins granted this scope in [config/grants.yml](https://github.com/mozilla/community-tc-config/blob/main/config/grants.yml). I'll see if there are clues from previous PRs, if new scopes appear in the diff.

**Comment by jwhitlock** [comment]
If I generate the YAML for the ``main`` branch locally (`tc-admin generate --without-secrets> main.yml`), and then generate the YAML for this PR, then I see the addition of this permission:

```yaml
  Role=hook-id:project-bugbug/bugbug*:
    roleId: hook-id:project-bugbug/bugbug*
    description:
      *DO NOT EDIT* - This resource is configured automatically.


    scopes:
      - assume:project:bugbug/build
      - assume:project:bugbug/deploy
      - auth:aws-s3:read-write:communitytc-bugbug/*
      - hooks:trigger-hook:project-bugbug/bugbug*
      - notify:email:*
      - queue:route:index.project.bugbug*
      - queue:route:notify.email.*
      - queue:route:notify.irc-channel.#bugbug.on-failed
      - queue:route:notify.pulse.route.project.bugbug.*
      - queue:route:project.bugbug.*
      - secrets:get:project/bugbug/production
``` 

However if I fetch the current configuration (`TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com tc-admin current --without-secrets> current.yml`), then the hook already has the ``notify:email:*`` scope. This is why the ``tc-admin diff`` test shows no changes.

It seems this PR is just catching the repo up with a change that has already been applied manually, so +1. However, if you were hoping this PR would change community-tc, we may need to dig deeper.

**Review by jwhitlock — APPROVED** [review]

**Comment by marco-c** [comment]
> It seems this PR is just catching the repo up with a change that has already been applied manually, so +1. However, if you were hoping this PR would change community-tc, we may need to dig deeper.

Yeah, I had applied the change manually for testing purposes!

**Comment by marco-c** [comment]
> It seems this PR is just catching the repo up with a change that has already been applied manually, so +1. However, if you were hoping this PR would change community-tc, we may need to dig deeper.

Yeah, I had applied the change manually for testing purposes!

**Comment by marco-c** [comment]
> It seems this PR is just catching the repo up with a change that has already been applied manually, so +1. However, if you were hoping this PR would change community-tc, we may need to dig deeper.

Yeah, I had applied the change manually for testing purposes!

**Pull request merged**
