### PR TITLE
update tc-admin

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by djmitche** [comment]
Pete, can you check this fixes the issue you saw in #12?

**Comment by djmitche** [comment]
https://github.com/taskcluster/tc-admin/releases/tag/v1.1.0

**Comment by milescrabill** [comment]
I tested w/ both `1.0.0` and `1.1.0` replicating Pete's config from slack messages and interestingly, both worked for me.

**Comment by djmitche** [comment]
Yeah, it's dependent on circumstances, which is why I missed it to start with.  I think if you run `python setup.py test` then it installs pytest, so if you do that before checking for this bug, you won't see it.  I think :)

Thanks!

**Pull request merged**
