### PR TITLE
Bug 1665052 - use updated docker-worker images

### PR DESCRIPTION
**Pull request by djmitche**
These are the images built in
https://github.com/taskcluster/monopacker/pull/85

### CODE REVIEW

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster/issues/3521

**Comment by djmitche** [comment]
Comments in https://bugzilla.mozilla.org/show_bug.cgi?id=1665052 but these latest images are:
 - d-w 30.1.1
 - confirmed to contain the latest monopacker
 - successfully run test tasks with loopback audio/video and a decision task to test for taskcluster/taskcluster#3521

**Review by petemoore — APPROVED** [review]
The scope of the change looks correct, and since your sample tasks ran successfully, it is likely that the image names are also correct (at least the ones the test tasks used). Many thanks!

**Comment by djmitche** [comment]
applied

**Pull request merged**
