### PR TITLE
add support for the json-e/json-e repository

### PR DESCRIPTION
**Pull request by djmitche**
See https://github.com/json-e/json-e/issues/430

This leaves JSON-e in the "taskcluster" project.  I think that will be easiest for the moment.

### CODE REVIEW

**Review by jwhitlock — APPROVED** [review]
Thanks @djmitche!

It has this scope with a notification:

```
scopes:
      - queue:route:notify.email.taskcluster-notifications@mozilla.com.*
      - secrets:get:project/taskcluster/json-e-deploy
```
I'm not sure if this means "send this email", or if it just allows sending the email. There may be a way to email the json-e maintainers instead

**Comment by jwhitlock** [comment]
Applied to https://community-tc.services.mozilla.com/

**Comment by djmitche** [comment]
Thanks!  We'd have to make a mailing list for the maintainers, which is probably not worth the trouble.

**Comment by jwhitlock** [comment]
I thought the Github teams had an email feature, but it is a team discussion feature that is on the website and doesn't have a mailbox. I agree, probably not worth the trouble.

**Pull request merged**
