### PR TITLE
Add libmozdata deployment secret

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Review by jwhitlock — APPROVED** [review]
Looks good to me. @marco-c - do you want me to apply the role change, or do you want to do it?

**Comment by marco-c** [comment]
@jwhitlock it'd be great if you could do it (I don't know how).

**Comment by jwhitlock** [comment]
I'm unable to deploy this myself, because I lack the scope that allows me to read the secret (``secrets:get:project/relman/libmozdata/deploy``). Let's connect over Slack when we're both online tomorrow and talk next steps.

**Comment by petemoore** [comment]
> I'm unable to deploy this myself, because I lack the scope that allows me to read the secret (`secrets:get:project/relman/libmozdata/deploy`). Let's connect over Slack when we're both online tomorrow and talk next steps.

I've applied the changes. @jwhitlock In general you probably need to use `pass show community-tc/root` to run `tc-admin`. We should probably add that to the docs...

**Pull request merged**
