### PR TITLE
chore: migrate `proj-mozci` to gw

### LINKED ISSUE #619: Migrate `mozci` project to Generic Worker

### PR DESCRIPTION
**Pull request by matt-boris**
Fixes #619.

### CODE REVIEW

**Review by lotas — COMMENTED** [review]
Test GitHub mobile app

**Comment by matt-boris** [comment]
Lots of exceptions https://community-tc.services.mozilla.com/tasks/groups/B3zujI4ySuGqAVKEyXd57g

**Comment by matt-boris** [comment]
Got farther now https://community-tc.services.mozilla.com/tasks/groups/el3HLSEiQuum_eyCp03JIg. Now I've opened up https://github.com/mozilla/mozci/pull/1035 to add the required scope for these tasks to run.

**Comment by matt-boris** [comment]
All's successful! https://community-tc.services.mozilla.com/tasks/groups/MC1iLl_rRGeB5EH9ON1amg

This actually uncovered a mozci bug that docker worker was hiding. Because generic worker fails if defined artifacts aren't available on the worker, it was failing certain tasks. Marco fixed them with https://github.com/mozilla/mozci/commit/ba9cd8e6ac2d479959f0c1217dfc3a38530ce3ee.

**Comment by matt-boris** [comment]
Got a small scopes issue https://community-tc.services.mozilla.com/tasks/DD69pX-jQCadohwp98A3lw/runs/0/logs/live/public/logs/live.log.

**Review by lotas — APPROVED** [review]
👍  thanks!

**Pull request merged**
