### PR TITLE
Align Windows Server 2022 worker pools, delete project bergamot

### PR DESCRIPTION
**Pull request by petemoore**
Note, this should not be merged and landed until Monday 5 June, to give stakeholders a chance to object.

CC @jschwartzentruber @choller @pyoor @glandium @marco-c @sylvestre @matt-boris @lotas @kdavis-mozilla

1. In an effort to reduce maintenance burden, we intend to install the following components on your Windows Server 2022 worker pools:

  *  Windows 10 SDK
  * Visual Studio 2019 Community Edition

These components are installed already on Release Management worker pools, and we would like to keep worker pools aligned for simplicity.

2. We intend to completely delete project bergamot - we believe it is no longer used (last updated by Kelly in 2020)

If you have any objections to the above, please comment in the PR. We intend to apply the changes on Monday 5 June.
Please also feel free to confirm your approval in the PR too.

### CODE REVIEW

**Review by marco-c — APPROVED** [review]

**Review by jschwartzentruber — APPROVED** [review]

**Comment by glandium** [comment]
I'll just mention that as far as Firefox CI is concerned, we don't need Windows 10 SDK or VS preinstalled.

**Comment by petemoore** [comment]
> I'll just mention that as far as Firefox CI is concerned, we don't need Windows 10 SDK or VS preinstalled.

Thanks @glandium!

Note, this change is only for community cluster workers, and from you I'm specifically interested in worker pool `proj-git-cinnabar/win2012r2`. Not all projects need the Win10 SDK or VS 2019 Community, but having a single base image will hopefully make maintenance easier for us, so if it doesn't break anything for your tasks, we'd like to align on base image if possible. Can you confirm having them installed won't cause a problem? Thanks!

Side note: since we updated the Windows base image to Windows Server 2022, `proj-git-cinnabar/win2012r2` now runs Windows Server 2022. It might be worth renaming it, e.g. to `proj-git-cinnabar/windows-server-2022` or `proj-git-cinnabar/windows-server`.

**Comment by petemoore** [comment]
For clarity, here are the affected worker pools:

* `proj-git-cinnabar/win2012r2`
Win10 SDK and VS 2019 Community will be installed
Approval required: @glandium

* `proj-fuzzing/ci-windows`
Win10 SDK and VS 2019 Community will be installed
Approval already granted by @jschwartzentruber

* `proj-taskcluster/gw-windows-2022` and `proj-taskcluster/gw-ci-windows-2022`
Win10 SDK and VS 2019 Community will be installed
Approval already granted by @lotas (and @petemoore)

* `proj-bergamot/ci-linux` and `proj-bergamot/ci-windows`
Both worker pools to be DELETED.
No current mozilla employees known to be associated with this project.
Last touched here, as far as I can tell: https://github.com/mozilla/marian-dev/pull/1
Seems to be unused.
@sylvestre Do you know anyone that needs to approve this, or can we just remove them?

* `proj-relman/win2022`
This pool has already been updated; no change required.
Change was approved (and authored!) by @marco-c

**Comment by marco-c** [comment]
You can go ahead with the removal of the Bergamot worker pools, we are not using them anymore.

**Comment by glandium** [comment]
Ah, yeah, no, git-cinnabar CI doesn't use VS either. I'm fine with the pool not changing name, that avoids having to change the configuration :)

**Comment by petemoore** [comment]
All approvals have been granted, so I'll land this already. Thanks everyone!

**Pull request merged**
