### PR TITLE
Deploy docker-worker 29.6.0

### PR DESCRIPTION
**Pull request by djmitche**
This is already applied on the proj-taskcluster/* workers, but once r+'d I'll land it for the rest.

### CODE REVIEW

**Comment by djmitche** [comment]
Fixes taskcluster/taskcluster#2856

**Comment by djmitche** [comment]
https://community-tc.services.mozilla.com/tasks/W3NTy3axQ1GiaIfLwkwtgQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FW3NTy3axQ1GiaIfLwkwtgQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
```
[taskcluster:error] Docker configuration could not be created.  This may indicate an authentication error when validating scopes necessary for running the task. 
 TypeError: taskVolumeBindings is not iterable
    at buildVolumeBindings (/home/ubuntu/docker-worker/src/lib/task.js:101:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Task.dockerConfig (/home/ubuntu/docker-worker/src/lib/task.js:389:22)
    at Task.run (/home/ubuntu/docker-worker/src/lib/task.js:889:22)
    at Task.start (/home/ubuntu/docker-worker/src/lib/task.js:702:17)
    at TaskListener.runTaskset (/home/ubuntu/docker-worker/src/lib/task_listener.js:525:9)
    at async Promise.all (index 0)
[taskcluster 2020-05-22 15:02:48.312Z] Unsuccessful task run with exit code: -1 completed in 1.231 seconds
```

**Comment by djmitche** [comment]
I rolled this back on TC CI

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster/pull/2874

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster/pull/2897
https://github.com/taskcluster/taskcluster/pull/2896

**Comment by petemoore** [comment]
(removed the review request as I think this is still draft, and we'll need new machine images to pick up the latest fixes)

**Comment by djmitche** [comment]
See #279.

**Pull request closed without merging**
